services:
  trex:
    command: npm run startdev
    build:
      context: ./services/trex
      dockerfile: Dockerfile
    ports:
      - 9229:9229
      - 25432:5432
    volumes:
      - ${D2E_FUNCTIONS:-./functions}:/usr/src/plugins/d2ef
      - ${D2E_FHIRFUNCTIONS:-./fhir_functions}:/usr/src/plugins/fhir
      - ./plugins/chat_functions:/usr/src/plugins/chat
      - ./ui/package.json:/usr/src/plugins/d2e-ui/package.json # For local ui development only
      # - ./ui/resources:/usr/src/local-resources # For local ui development only
      # - ./services/trex/core:/usr/src/core # For debugging trex with local code
      # - ./flows/base/package.json:/usr/src/plugins/d2e-flows/package.json # For local flows development only
    environment:
      RUST_LOG: info
      RUST_BACKTRACE: full
      LOCAL_DEBUG: "true"
      DATABASE_CREDENTIALS: ${DATABASE_CREDENTIALS:-{}}
      PLUGINS_SEED: '["d2e-flows", "d2e-ui", "d2e-atlas"]'
      PLUGINS_SEED_UPDATE: ${PLUGINS_SEED_UPDATE:-false}
      PLUGINS_DEV_PATH: "./plugins"
      WATCH: |-
        {
          "analytics-svc": false,
          "mri-pg-config": false,
          "alp-fhir-svc": false,
          "alp-fhir-init": false,
          "alp-dataflow-gen-init": false,
          "query-gen-svc": false,
          "alp-usermgmt": false,
          "bookmark-svc": false,
          "mri-pa-config": false,
          "cdw-svc": false,
          "jobplugins": false,
          "dataset": false,
          "alpdb": false,
          "concept-mapping": false,
          "terminology-svc": false,
          "code-suggestion": false,
          "data-mapping": false,
          "portal": false,
          "files-manager": false,
          "demo": false,
          "d2e-webapi": false,
          "perseus": false,
          "white-rabbit": false,
          "strategus-results": false
        }

  alp-caddy:
    command: caddy run --environ --config /srv/caddy-config/Caddyfile --adapter caddyfile --watch
    image: caddy:2.8-alpine
    ports:
      - 41000:41000
      - 41130:41130
    volumes:
      - ${CADDY__CONFIG:-./deploy/caddy-config}:/srv/caddy-config
    environment:
      CADDY__FHIR_SERVER__PUBLIC_FQDN: ${CADDY__FHIR_SERVER__PUBLIC_FQDN:-localhost}
      CADDY__CORS_LOCAL_UI: "import cors"

  alp-dataflow-gen:
    ports:
      - 41120:41120
    environment:
      SYSTEM_PORTAL__API_URL: https://trex:33000/system-portal/

  alp-logto:
    build:
      context: ./services/alp-logto
      dockerfile: Dockerfile

  alp-minerva-pg-mgmt-init:
    ports:
      - 9211:9211
    build:
      context: services/alp-pg-management
      dockerfile: Dockerfile
    volumes:
      - ./services/alp-pg-management/app:/home/docker/app

  alp-minerva-postgres:
    ports:
      - 41190:5432
      - 5432:5432

  demodb:
    ports:
      - "15432:5432"

  alp-minerva-s3:
    ports:
      # - 9000:9000 #Port for API connectivity, internal communication is good enough. Needs to be uncommented only when testing from outside the alp docker network
      - 9090:9090

  dicom-server:
    # uses 8042 port on the container
    ports:
      - 8042:8042

  alp-logto-post-init:
    build:
      context: ./services/alp-logto/post-init
      dockerfile: Dockerfile
    # volumes:
    #   - ./services/alp-logto/post-init:/home/docker

  # alp-fhir-server-post-init:
  #   build:
  #     context: .
  #     dockerfile: ./services/alp-fhir/Dockerfile.client
  #   volumes:
  #     - ./services/alp-fhir/dist:/home/docker/src/alp-data-node/app/dist
  #     - ./services/alp-fhir/src:/home/docker/src/alp-data-node/app/src
  #   environment:
  #     LOCAL_DEBUG: "true"
  #   ports:
  #     - 9226:9226

  alp-cachedb:
    build:
      context: .
      dockerfile: ./services/cachedb/Dockerfile
      target: development
      # To test without Hana
      # args:
      #   BUILD_TYPE: OSS
    volumes:
      - ./services/cachedb/src:/home/docker/src
    ports:
      - 9235:9235
      - 41191:41191
    environment:
      LOCAL_DEBUG: "true"

  fhir-server:
    build:
      context: ./services/alp-fhir
      dockerfile: Dockerfile

  # fhir-fe-server:
  #   build:
  #     context: ./services/alp-fhir/
  #     dockerfile: Dockerfile.frontend
  #   volumes:
  #     - ./services/alp-fhir/ui-file-server/index.js:/home/docker/index.js
  #   ports:
  #     - 41130:3000

  enterprise-gateway:
    build:
      context: ./services/enterprise-gateway
      dockerfile: Dockerfile
    environment:
      EG_ALLOW_ORIGIN: "https://${CADDY__ALP__PUBLIC_FQDN:-localhost}${PORT:+:${PORT:-41100}}"
    volumes:
      - ./services/enterprise-gateway/r-strategus-lib/rD2E:/app/rD2E
      - ./services/enterprise-gateway/kernels/R_ohdsi_docker:/usr/local/share/jupyter/kernels/R_ohdsi_docker
  mlflow:
    ports:
      - "5000:5000"
    build:
      context: ./flows
      dockerfile: ./base/Dockerfile