import { test, expect } from '@playwright/test'

test('test', async ({ page }) => {
  await page.goto('https://localhost:443/portal')
  await page.locator('input[name="identifier"]').click()
  await page.locator('input[name="identifier"]').fill('admin')
  await page.locator('input[name="identifier"]').press('Tab')
  await page.getByRole('button').filter({ hasText: /^$/ }).press('Tab')
  await page.locator('input[name="password"]').fill('Updatepassword12345')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.getByTestId('button').nth(1).click()
  await page.getByRole('button', { name: 'Switch to Admin portal' }).click()
  await page.getByTestId('button').click()
  await page.getByRole('textbox', { name: 'Username' }).click()
  // Generate a random number for the role name to avoid conflicts
  const roleName = `grant_admin_role_${Math.floor(Math.random() * 10000)}`
  await page.getByRole('textbox', { name: 'Username' }).fill(roleName)
  await page
    .locator('div')
    .filter({ hasText: /^Password$/ })
    .click()
  await page.getByRole('textbox', { name: 'Password' }).fill('Updatepassword12345')
  await page.waitForTimeout(2000)
  await page.getByRole('button', { name: 'Add' }).click()
  await page.getByTestId('table-row').filter({ hasText: roleName }).getByRole('button', { name: 'Edit' }).click()
  await page.getByTestId('dialog').getByText('Admin', { exact: true }).click()
  await page.getByTestId('dialog').getByText('User Admin').click()
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(page.locator('tbody')).toContainText('ViewerAdminUser Admin')
  await page.getByRole('link', { name: 'Account' }).click()
  await page.getByRole('button', { name: 'Logout' }).click()
  await page.locator('input[name="identifier"]').click()
  await page.locator('input[name="identifier"]').fill(roleName)
  await page.locator('input[name="password"]').click()
  await page.locator('input[name="password"]').fill('Updatepassword12345')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByTestId('nav')).toContainText('Datasets')
  await expect(page.getByTestId('nav')).toContainText('Users')
  await page.getByRole('link', { name: 'Account' }).click()
  await page.getByRole('button', { name: 'Logout' }).click()
  await page.locator('input[name="identifier"]').click()
  await page.locator('input[name="identifier"]').fill('admin')
  await page.locator('input[name="identifier"]').press('Tab')
  await page.getByRole('button').filter({ hasText: /^$/ }).press('Tab')
  await page.locator('input[name="password"]').fill('Updatepassword12345')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.getByTestId('button').nth(1).click()
  await page.getByRole('button', { name: 'Switch to Admin portal' }).click()
  await page.getByTestId('table-row').filter({ hasText: roleName }).getByRole('button', { name: 'Delete' }).click()
  await page.getByRole('button', { name: 'Yes, delete' }).click()
})
