import { test, expect } from '@playwright/test'

const TEST_NAME = 'parent-interaction'
const SHOULD_SKIP = true
test.fixme(SHOULD_SKIP, `${TEST_NAME} test is temporarily disabled.`)

test(TEST_NAME, async ({ page }) => {
  await page.goto('https://localhost:443/portal')
  await page.locator('input[name="identifier"]').click()
  await page.locator('input[name="identifier"]').fill('admin')
  await page.locator('input[name="identifier"]').press('Tab')
  await page.locator('input[name="password"]').click()
  await page.locator('input[name="password"]').fill('Updatepassword12345')
  await page.getByRole('button', { name: 'Sign in' }).click()

  await page.getByText('Demo dataset').first().click()
  await page.getByRole('link', { name: 'Cohorts' }).click()
  await expect(page.getByRole('status')).toBeVisible()
  await expect(page.getByRole('status')).toBeHidden()
  await page.getByRole('button', { name: 'D2E' }).click()
  await expect(page.locator('.loading-animation-component')).toBeVisible()
  await expect(page.locator('.loading-animation-component')).toBeHidden()
  await expect(page.getByText('2694 / 2694')).toBeVisible()
  await page.getByTitle('Add Filter Card').getByRole('button').click()
  await page.getByRole('menuitem', { name: 'Visit' }).click()
  await page.getByTitle('Add Filter Card').getByRole('button').click()
  await page.getByRole('menuitem', { name: 'Condition Occurrence' }).click()
  await page.getByRole('tab', { name: ' Condition Occurrence A ' }).locator('button').last().click()
  await page.getByRole('menuitem', { name: 'Visit Occurrence Parent' }).click()
  await expect(page.getByText('890 / 2694')).toBeVisible()

  //UI issues with CDW Config, will skip for now

  // await page.getByRole('link', { name: 'Account' }).click()
  // await page.getByRole('button', { name: 'Switch to Admin portal' }).click()
  // await page.getByRole('link', { name: 'Setup' }).click()
  // await page
  //   .locator('div')
  //   .filter({ hasText: /^CDM ConfigConfigure CDMConfigure$/ })
  //   .getByTestId('button')
  //   .click()
  // await page.getByText('OMOP_DM').click()
  // await page.getByText('1', { exact: true }).click()
  // await page.getByText('1', { exact: true }).click()
  // await page.locator('[id="__item2-img"]').click()
  // await page.getByRole('form', { name: 'Placeholder @PROC $$SCHEMA' }).getByLabel('Hierarchy Support').click()
  // await expect(
  //   page.getByRole('form', { name: 'Placeholder @PROC $$SCHEMA' }).getByLabel('Hierarchy Support')
  // ).toBeChecked()
  // await page.getByRole('option', { name: 'Data Model Settings' }).click()
  // await page.getByRole('heading', { name: 'Defined Interactions (19)' }).click()
  // await page.getByText('Procedure OccurrenceAttributes(10)DuplicateDelete').click()
  // await page.locator('[id="__button180"]').click()
  // await page.getByLabel('Are you sure you want to').getByRole('button', { name: 'Delete' }).click()
  // await page.getByText('Procedure Occurrence').click()
  // await page.getByRole('list', { name: 'Tokenizer' }).click()
  // await page.locator('[id="__xmlview5--pInteractionDDId-inner"]').click()
  // await page.locator('[id="__xmlview5--pInteractionDDId-arrow"]').click()
  // await page.locator('[id="__item138-selectMulti"]').click()
  // await page.locator('[id="__layout11"] div').filter({ hasText: 'Parent Interaction:' }).first().click()
  // await expect(page.getByRole('listitem', { name: 'Visit' })).toBeVisible()
  // await page.locator('[id="__xmlview5--pInteractionLabel-inner"]').click()
  // await expect(page.locator('[id="__xmlview5--pInteractionLabel-inner"]')).toBeVisible()
  // await page.locator('[id="__xmlview5--pInteractionLabel-inner"]').click()
  // await page.getByText('Filter Control Label for').click()
  // await page.getByRole('button', { name: 'Save & Activate' }).click()
  // await expect(page.locator('#sap-ui-blocklayer-popup')).toBeVisible()
  // await page.getByRole('button', { name: 'OK' }).click()
  // await page.getByRole('button', { name: 'Back' }).click()
  // await page.getByRole('button').filter({ hasText: /^$/ }).first().click()
  // await page
  //   .locator('div')
  //   .filter({ hasText: /^Patient Analytics configConfigure patient analyticsConfigure$/ })
  //   .getByTestId('button')
  //   .click()
  // await page.locator('[id="__xmlview20--dataModelConfigurationsCombo-arrow"]').click()
  // await page.getByRole('option', { name: 'OMOP_DM' }).click()
  // await page.locator('[id="__xmlview22--dataModelVersionCombo-arrow"]').click()
  // await page.getByRole('option', { name: '- Active Version' }).click()
  // await page.getByRole('button', { name: 'Keep Current Settings' }).click()
  // await expect(page.getByRole('textbox', { name: 'Clinical Data Model Version :' })).toBeVisible()
  // await page.getByRole('button', { name: 'Save' }).click()
  // await expect(page.getByText('Configuration saved.')).toBeVisible()
  // await page.getByRole('link', { name: 'Account' }).click()
  // await page.getByRole('button', { name: 'Switch to Researcher portal' }).click()

  // await page.getByTestId('card').first().click()
  // await page.getByRole('link', { name: 'Cohorts' }).click()
  // await expect(page.getByRole('status')).toBeVisible()
  // await expect(page.getByRole('status')).toBeHidden()
  // await page.getByTitle('Add Filter Card').getByRole('button').click()
  // await page.getByRole('menuitem', { name: 'Visit' }).click()
  // await page.getByTitle('Add Filter Card').getByRole('button').click()
  // await page.getByRole('menuitem', { name: 'Procedure Occurrence' }).click()
  // await page.getByRole('tab', { name: ' Procedure Occurrence A ' }).locator('button').last().click()
  // await page.getByRole('menuitem', { name: 'parent' }).click()
  // await page.getByText('None').first().click()
  // await expect(page.getByText('None').first()).toBeVisible()
  // await page.getByText('None').first().click()
  // await page.locator('span').filter({ hasText: 'Visit A' }).nth(3).click()
  // await page.locator('.modal-wrapper').click()
  // await expect(page.getByText('936 / 1000')).toBeVisible()

  // await page.getByTitle('Add Filter Card').getByRole('button').click()
  // await page.getByRole('menuitem', { name: 'Death' }).click()
  // await page.getByRole('tab', { name: ' Death A ' }).locator('button').last().click()
  // await expect(page.getByRole('menuitem', { name: 'Visit Occurrence Parent' })).toBeHidden()
})
