import { test, expect } from '@playwright/test'

const TEST_NAME = 'Change Password and Logout'
const SHOULD_SKIP = false
test.fixme(SHOULD_SKIP, `${TEST_NAME} test is temporarily disabled.`)

test(TEST_NAME, async ({ page }) => {
  await page.goto('https://localhost:443/portal')
  await page.locator('input[name="identifier"]').click()
  await page.locator('input[name="identifier"]').fill('admin')
  await page.locator('input[name="password"]').click()
  await page.locator('input[name="password"]').fill('Updatepassword12345')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.getByTestId('button').nth(1).click()
  await expect(page.getByRole('main')).toContainText('admin')
  await page.getByRole('button', { name: 'Change password' }).click()
  await expect(page.getByTestId('dialog-title')).toContainText('Change password')
  await page.getByRole('textbox', { name: 'Old password' }).click()
  await page.getByRole('textbox', { name: 'Old password' }).fill('Updatepassword12345')
  await page.getByRole('button', { name: 'Generate' }).click()
  await expect(page.getByRole('textbox', { name: 'New password' })).not.toHaveValue('')
  await page.getByRole('textbox', { name: 'New password' }).click()
  await page.getByRole('textbox', { name: 'New password' }).fill('Updatepassword123456')
  await page.getByRole('button', { name: 'Hide password' }).click()
  await page.getByRole('button', { name: 'Update' }).click()
  await expect(page.getByTestId('snackbar-message')).toContainText('Password updated')
  await page.getByTestId('dialog-close').click()
  await page.getByRole('button', { name: 'Logout' }).click()
  await page.locator('input[name="identifier"]').click()
  await page.locator('input[name="identifier"]').fill('admin')
  await page.locator('input[name="password"]').click()
  await page.locator('input[name="password"]').fill('Updatepassword123456')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.getByTestId('button').nth(1).click()
  await page.getByRole('button', { name: 'Change password' }).click()
  await page.getByRole('textbox', { name: 'Old password' }).click()
  await page.getByRole('textbox', { name: 'Old password' }).fill('Updatepassword123456')
  await page.getByRole('textbox', { name: 'New password' }).click()
  await page.getByRole('textbox', { name: 'New password' }).fill('Updatepassword12345')
  await page.getByRole('button', { name: 'Update' }).click()
  await expect(page.getByTestId('snackbar-message')).toContainText('Password updated')
  await page.getByTestId('dialog-close').click()
  await page.getByRole('button', { name: 'Logout' }).click()
  await expect(page).toHaveScreenshot({ maxDiffPixels: 100 })
})
