import { ITokenUser } from './types'

export const ROLES = {
  ALP_USER_ADMIN: 'ALP_USER_ADMIN',
  ALP_SYSTEM_ADMIN: 'ALP_SYSTEM_ADMIN',
  ALP_NIFI_ADMIN: 'ALP_NIFI_ADMIN',
  ALP_DASHBOARD_VIEWER: 'ALP_DASHBOARD_VIEWER',
  TENANT_ADMIN: 'TENANT_ADMIN',
  TENANT_VIEWER: 'TENANT_VIEWER',
  STUDY_ADMIN: 'STUDY_ADMIN',
  STUDY_MANAGER: 'STUDY_MGR',
  STUDY_RESEARCHER: 'RESEARCHER',
  STUDY_WRITE_DQD_RESEARCHER: 'STUDY_WRITE_DQD_RESEARCHER',
  ALP_SHARED: 'ALP_SHARED'
}

export const GROUP_NAME_PARTS = {
  TID: 'TID',
  STUDYID: 'SID',
  ROLE: 'ROLE'
}

export const DEMO_USER: ITokenUser = {
  userId: 'e30e6fa8-5064-4adc-af88-e9e00ad78198'
}

export const INVITE_EXPIRY_SECONDS = 604800

export const CONTAINER_KEY = {
  DB_CONNECTION: 'DB_CONNECTION',
  AUTHORIZATION_HEADER: 'AUTHORIZATION_HEADER',
  CURRENT_USER: 'CURRENT_USER'
}

export const CONFIG_KEY = {
  ROLE_TENANT_VIEWER_GROUP_ID: 'ROLE_TENANT_VIEWER_GROUP_ID',
  ROLE_SYSTEM_ADMIN_GROUP_ID: 'ROLE_SYSTEM_ADMIN_GROUP_ID',
  ROLE_USER_ADMIN_GROUP_ID: 'ROLE_USER_ADMIN_GROUP_ID'
}

export const IDP_SCOPE_ROLE = {
  SYSTEM_ADMIN: 'role.systemadmin',
  USER_ADMIN: 'role.useradmin',
  DASHBOARD_VIEWER: 'role.dashboardviewer',
  DATASET_RESEARCHER_PREFIX: 'role.researcher.'
}
