# docker compose -f flows/hades/strategus_plugin/dc-local.yml up -d
services:
  app:
    platform: linux/amd64
    image: ghcr.io/ohdsi/d2e/flow-hades:develop
    # with debugger listening
    # entrypoint: python -m debugpy --listen 0.0.0.0:9234 --wait-for-client -m flows.hades.strategus_plugin.flow
    entrypoint: /app/.venv/bin/python -m pytest /app/flows/hades/strategus_plugin/tests/
    environment:
      - PREFECT_API_URL=http://dataflow-gen-1:41120/api
      - IS_DEV_ENV=true
    ports:
      - 9234:9234
    volumes:
      - ../../../flows:/app/flows
      - ../../../flows/_shared_flow_utils:/app/_shared_flow_utils
    networks:
      - alp

networks:
  alp:
    # name: alp_alp
    # external: true