name: d2e/demosetup-dev

on:
  workflow_dispatch: # Allow manual triggering
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - develop

env:
  VERSION: develop


jobs:
  demosetup:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: npm install
        if: success() || failure()
        run: |
          npm install 

      - name: Initialise d2e
        if: success() || failure()
        id: init
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v develop init

      - name: Build docker images
        if: success() || failure()
        id: pull
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v develop -d ./functions build
          docker images --format "table {{.ID}}\t{{.Repository}}\t{{.Tag}}"

      - name: Start services
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: start
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 1
          retry_on: any
          command: |
            ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v ${{ env.VERSION }}  -d ./functions start
            DC_EXIT_CODE=$?
            DOCKER_STATUS_FILE=../docker-status-${GITHUB_RUN_ID:-ghRunId}-$(date '+%Y%m%dT%H%M%S').txt | tee -a $GITHUB_ENV
            docker ps --format {{.Names}},{{.Status}} 2> /dev/null | sort | tee $DOCKER_STATUS_FILE | tee -a $GITHUB_STEP_SUMMARY
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }
      
      - name: Log status
        if: success() || failure()
        run: |
          echo DC_EXIT_CODE=$DC_EXIT_CODE | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_EXIT_CODE=${{ steps.start.outputs.exit_code }} | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_OUTCOME=${{ steps.start.outcome }} | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_TOTAL_ATTEMPTS=${{ steps.start.outputs.total_attempts }} | tee -a $GITHUB_STEP_SUMMARY
          DC_FAIL_COUNT=$(grep -icE "starting|unhealthy" $DOCKER_STATUS_FILE|| true)
          echo DC_FAIL_COUNT=$DC_FAIL_COUNT | tee -a $GITHUB_STEP_SUMMARY
      
      - name: Logs 
        if: success() || failure()
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v ${{ env.VERSION }} -d ./functions logs

      - name: Setupdemo
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: setupdemo
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 1
          retry_on: any
          command: |
            ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v ${{ env.VERSION }}  -d ./functions setupdemo
            DC_EXIT_CODE=$?
            DOCKER_STATUS_FILE=../docker-status-${GITHUB_RUN_ID:-ghRunId}-$(date '+%Y%m%dT%H%M%S').txt | tee -a $GITHUB_ENV
            docker ps --format {{.Names}},{{.Status}} 2> /dev/null | sort | tee $DOCKER_STATUS_FILE | tee -a $GITHUB_STEP_SUMMARY
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }
  
      - name: Logs 
        if: success() || failure()
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v ${{ env.VERSION }} -d ./functions logs

      - name: Checkflow
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: checkflow
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 1
          retry_on: any
          command: |
            ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v ${{ env.VERSION }} -d ./functions checkflow
            DC_EXIT_CODE=$?
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }

      - name: Restart d2e services
        if: success() || failure()
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v ${{ env.VERSION }} -d ./functions stop
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v ${{ env.VERSION }} -d ./functions start

      - name: e2e tests setup
        run: |
          cd ./tests/e2e
          npm install
          npm run init

      - name: e2e tests
        # continue-on-error: true
        run: |
          cd ./tests/e2e
          npm test

      - name: Upload Error Context
        if: always()  # Always run, even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: error-context
          path: tests/e2e/test-results/**/*

      - name: Logs 
        if: success() || failure()
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v ${{ env.VERSION }} -d ./functions logs

      - name: Publish Test Report
        if: always()
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './tests/e2e/ctrf/*.json'
          file-report: true
        
      - name: Stop d2e services
        if: success() || failure()
        id: stop
        run: |
          ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v ${{ env.VERSION }} -d ./functions stop
      - name: Clean d2e services
        if: success() || failure()
        id: clean
        run: |
          echo "y" | ENV_TYPE=remote CADDY__CONFIG=./deploy/caddy-config ./scripts/cli.sh -e -v ${{ env.VERSION }} -d ./functions clean