name: d2e/demosetup-release

on:
  schedule:
    - cron: "0 22 * * *" # UTC timing
  workflow_dispatch:
    inputs:
      version:
        default: 0.8.1
        description: Enter version to use
        required: true
        type: string

jobs:
  demosetup:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install latest cli
        if: success() || failure() 
        id: install
        run: |
          npm i -g d2e
      
      - name: Initialise d2e
        if: success() || failure()
        id: init
        run: |
          d2e init 

      - name: Pull docker images
        if: success() || failure()
        id: pull
        run: |
          d2e -e pull
          docker images --format "table {{.ID}}\t{{.Repository}}\t{{.Tag}}"

      - name: Start services
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: start
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 3
          retry_on: any
          command: |
            d2e -e start
            DC_EXIT_CODE=$?
            DOCKER_STATUS_FILE=../docker-status-${GITHUB_RUN_ID:-ghRunId}-$(date '+%Y%m%dT%H%M%S').txt | tee -a $GITHUB_ENV
            docker ps --format {{.Names}},{{.Status}} 2> /dev/null | sort | tee $DOCKER_STATUS_FILE | tee -a $GITHUB_STEP_SUMMARY
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }
      
      - name: Log status
        if: success() || failure()
        run: |
          echo DC_EXIT_CODE=$DC_EXIT_CODE | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_EXIT_CODE=${{ steps.start.outputs.exit_code }} | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_OUTCOME=${{ steps.start.outcome }} | tee -a $GITHUB_STEP_SUMMARY
          echo RETRY_TOTAL_ATTEMPTS=${{ steps.start.outputs.total_attempts }} | tee -a $GITHUB_STEP_SUMMARY
          DC_FAIL_COUNT=$(grep -icE "starting|unhealthy" $DOCKER_STATUS_FILE|| true)
          echo DC_FAIL_COUNT=$DC_FAIL_COUNT | tee -a $GITHUB_STEP_SUMMARY
      
      - name: Logs 
        if: success() || failure()
        run: |
          d2e logs
 
      - name: Setupdemo
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: setupdemo
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 3
          retry_on: any
          command: |
            d2e -e setupdemo
            DC_EXIT_CODE=$?
            DOCKER_STATUS_FILE=../docker-status-${GITHUB_RUN_ID:-ghRunId}-$(date '+%Y%m%dT%H%M%S').txt | tee -a $GITHUB_ENV
            docker ps --format {{.Names}},{{.Status}} 2> /dev/null | sort | tee $DOCKER_STATUS_FILE | tee -a $GITHUB_STEP_SUMMARY
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }
  
      - name: Checkflow
        if: success() || failure()
        uses: nick-fields/retry@v3
        id: checkflow
        with:
          timeout_seconds: 1800
          retry_wait_seconds: 100
          max_attempts: 3
          retry_on: any
          command: |
            d2e checkflow
            DC_EXIT_CODE=$?
            [ $DC_EXIT_CODE = 0 ] || { echo EXIT DC_EXIT_CODE=$DC_EXIT_CODE && exit $DC_EXIT_CODE; }

      - name: Stop d2e services
        if: success() || failure()
        id: stop
        run: |
          d2e -e stop
      - name: Clean d2e services
        if: success() || failure()
        id: clean
        run: |
          echo "y" | d2e clean  

      - name: Discord notification on status
        if: success() || failure()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_DEVOPS }}
          username: ${{ github.actor }}
          content: "### Status of Installation\n
            install: ${{ steps.install.outcome }}\n
            init: ${{ steps.init.outcome }}\n
            pull: ${{ steps.pull.outcome }}\n
            start: ${{ steps.start.outcome }}\n
            patchdemodb: ${{ steps.patchdemodb.outcome }}\n
            setupdemo: ${{ steps.setupdemo.outcome }}\n
            checkflow: ${{ steps.checkflow.outcome }}\n
            stop: ${{ steps.stop.outcome }}"
